CREATE TABLE user
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_0
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_1
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_2
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_3
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_4
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_5
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_6
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_7
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_8
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE TABLE user_9
(
    id INT(11) IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL
);

CREATE VIEW all_user AS SELECT * FROM user_0
    UNION ALL SELECT * FROM user_1
    UNION ALL SELECT * FROM user_2
    UNION ALL SELECT * FROM user_3
    UNION ALL SELECT * FROM user_4
    UNION ALL SELECT * FROM user_5
    UNION ALL SELECT * FROM user_6
    UNION ALL SELECT * FROM user_7
    UNION ALL SELECT * FROM user_8
    UNION ALL SELECT * FROM user_9;